openapi: 3.1.3

info:
  title: traQ gazer
  description: |-
    部内連絡ツール traQ において登録された単語の通知を行うサービス
  version: 2.0.0

servers:
  - url: /api

tags:
  - name: words
    description: 単語の閲覧・追加・削除
  - name: stamps
    description: スタンプの閲覧・追加・削除
  - name: me
    description: 自分の情報

paths:
  /words:
    post:
      tags:
        - words
      summary: 単語の登録
      description: 同時に通知の設定もする
      parameters:
        - $ref: '#/components/parameters/NeoShowcase'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewWord'
      responses:
        '200':
          description: Successful registration
        '400':
          description: Invalid input

  /words/{wordId}:
    parameters:
      - $ref: '#/components/parameters/WordId'
      - $ref: '#/components/parameters/NeoShowcase'
    put:
      tags:
        - words
      summary: 通知除外者の設定
      description: 通知しない投稿者を指定する
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExcludedUsers'
      responses:
        '200':
          description: Successful edit
        '404':
          description: Not found
    delete:
      tags:
        - words
      summary: 単語の削除
      description: 自分が登録した単語を削除できる。ない場合は404
      responses:
        '200':
          description: Successful deletion
        '404':
          description: Not found

  /words/{wordId}/exclusions:
    parameters:
      - $ref: '#/components/parameters/WordId'
      - $ref: '#/components/parameters/NeoShowcase'
    put:
      tags:
        - words
      summary: 単語の通知除外者の設定
      description: 指定した単語について、通知しない投稿者一覧を上書きして設定
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExcludedUsers'
      responses:
        '200':
          description: Successful edit
        '404':
          description: Not found

  /stamps:
    parameters:
      - $ref: '#/components/parameters/NeoShowcase'
    get:
      tags:
        - stamps
      summary: スタンプの一覧
      description: traQ に登録されているスタンプの一覧を取得
      responses:
        '200':
          description: Successful retrieval
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stamps'
    post:
      tags:
        - stamps
      summary: スタンプの登録
      description: 同時に通知の設定もする
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewStamp'
      responses:
        '200':
          description: Successful registration
        '400':
          description: Invalid input

  /stamps/{stampId}:
    parameters:
      - $ref: '#/components/parameters/StampId'
      - $ref: '#/components/parameters/NeoShowcase'
    delete:
      tags:
        - stamps
      summary: スタンプの削除
      description: 自分が登録したスタンプを削除できる。ない場合は404
      responses:
        '200':
          description: Successful deletion
        '404':
          description: Not found

  /stamps/{stampId}/exclusions:
    parameters:
      - $ref: '#/components/parameters/StampId'
      - $ref: '#/components/parameters/NeoShowcase'
    put:
      tags:
        - stamps
      summary: スタンプの通知除外者の設定
      description: 指定したスタンプについて、通知しない投稿者一覧を上書きして設定
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExcludedUsers'
      responses:
        '200':
          description: Successful edit
        '404':
          description: Not found

  /me:
    parameters:
      - $ref: '#/components/parameters/NeoShowcase'
    get:
      tags:
        - me
      summary: 自分の情報の閲覧
      description: 自分の traP ID を取得
      responses:
        '200':
          description: Successful retrieval
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyInfo'
        '404':
          description: Not found

  /me/words:
    parameters:
      - $ref: '#/components/parameters/NeoShowcase'
    get:
      tags:
        - me
        - words
      summary: 自分の登録した単語の一覧
      description: 自分が登録した単語の一覧を取得
      responses:
        '200':
          description: Successful retrieval
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyWords'
        '404':
          description: Not found

  /me/stamps:
    parameters:
      - $ref: '#/components/parameters/NeoShowcase'
    get:
      tags:
        - me
        - stamps
      summary: 自分の登録したスタンプの一覧
      description: 自分が登録したスタンプの一覧を取得
      responses:
        '200':
          description: Successful retrieval
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyStamps'
        '404':
          description: Not found

components:
  schemas:
    NewWord:
      type: object
      description: sessionからuserIdを取る
      properties:
        wordValue:
          type: string
          example: "デジタル創作同好会traP"
        isRegex:
          type: boolean
          example: false
        excludedUsers:
          $ref: '#/components/schemas/ExcludedUsers'
      required:
        - wordValue
        - isRegex
        - excludedUsers
    ExcludedUsers:
      type: array
      items:
        $ref: '#/components/schemas/ExcludedUser'
    ExcludedUser:
      type: object
      properties:
        trapId:
          type: string
          example: "trap"
      required:
        - trapId
    
    MyWords:
      type: array
      items:
        $ref: '#/components/schemas/MyWord'
    MyWord:
      type: object
      properties:
        id:
          type: string
          format: uuid
        wordValue:
          type: string
        isRegex:
          type: boolean
          example: false
        excludedUsers:
          $ref: '#/components/schemas/ExcludedUsers'
      required:
        - id
        - wordValue
        - isRegex
        - excludedUsers
    
    NewStamp:
      type: object
      description: sessionからuserIdを取る
      properties:
        stampName:
          type: string
        excludedUsers:
          $ref: '#/components/schemas/ExcludedUsers'
      required:
        - stampName
        - excludedUsers
    
    MyStamps:
      type: array
      items:
        $ref: '#/components/schemas/MyStamp'
    MyStamp:
      type: object
      properties:
        id:
          type: string
          format: uuid
        stampName:
          type: string
        excludedUsers:
          $ref: '#/components/schemas/ExcludedUsers'
      required:
        - id
        - stampName
        - excludedUsers
    
    Stamps:
      type: array
      items:
        $ref: '#/components/schemas/Stamp'
    Stamp:
      type: object
      properties:
        name:
          type: string
        stampId:
          type: string
          format: uuid
      required:
        - name
        - stampId

    MyInfo:
      type: object
      properties:
        trapId:
          type: string
          example: "trap"
      required:
        - trapId

  parameters:
    WordId:
      in: path
      name: wordId
      description: 単語の uuid で指定する
      schema:
        type: string
        format: uuid
      required: true
    StampId:
      in: path
      name: stampId
      description: スタンプの uuid で指定する
      schema:
        type: string
        format: uuid
      required: true
    NeoShowcase:
      in: header
      name: X-Forwarded-User
      description: traP ID を取得するためのヘッダー
      schema:
        type: string
      required: true
