---------- external items ----------
CREATE TABLE IF NOT EXISTS `users` (
  `id` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `display_name` VARCHAR(32) NOT NULL,
  `traq_id` VARCHAR(32) NOT NULL UNIQUE,
  `traq_uuid` BINARY(16) NOT NULL UNIQUE,
  `is_bot` BOOLEAN NOT NULL,
  `is_expired` BOOLEAN NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `traq_stamps` (
  `id` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) NOT NULL,
  `traq_uuid` BINARY(16) NOT NULL UNIQUE,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

---------- internal items ----------
CREATE TABLE IF NOT EXISTS `word_subscriptions` (
  `id` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `uuid` BINARY(16) NOT NULL UNIQUE,
  `user_id` BIGINT(8) NOT NULL,
  `value` VARCHAR(50) NOT NULL,
  `is_regex` BOOLEAN NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `word_excluded_users` (
  `subs_id` BIGINT(8) NOT NULL,
  `user_id` BIGINT(8) NOT NULL,
  FOREIGN KEY (`subs_id`) REFERENCES `word_subscriptions`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `stamp_subscriptions` (
  `id` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `uuid` BINARY(16) NOT NULL UNIQUE,
  `user_id` BIGINT(8) NOT NULL,
  `stamp_id` BIGINT(8) NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (`stamp_id`) REFERENCES `traq_stamps`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `stamp_excluded_users` (
  `subs_id` BIGINT(8) NOT NULL,
  `user_id` BIGINT(8) NOT NULL,
  FOREIGN KEY (`subs_id`) REFERENCES `stamp_subscriptions`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `polling` (
  `key` INT NOT NULL,
  `last` datetime NOT NULL,
  PRIMARY KEY (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
