CREATE TABLE IF NOT EXISTS `users` (
  `id` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `trap_id` VARCHAR(32) NOT NULL,
  `traq_uuid` BINARY(16) NOT NULL,
  `is_bot` BOOLEAN NOT NULL,
  `is_expired` BOOLEAN NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `words` (
  `id` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `uuid` BINARY(16) NOT NULL,
  `user_id` BIGINT(8) NOT NULL,
  `value` VARCHAR(50) NOT NULL,
  `is_regex` BOOLEAN NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `word_excluded_users` (
  `word_id` BIGINT(8) NOT NULL,
  `user_id` BIGINT(8) NOT NULL,
  FOREIGN KEY (`word_id`) REFERENCES `words`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `stamps` (
  `stamp_id` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `stamp_uuid` BINARY(16) NOT NULL,
  `user_id` BIGINT(8) NOT NULL,
  `word` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`stamp_id`),
  FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `stamp_excluded_users` (
  `stamp_id` BIGINT(8) NOT NULL,
  `user_id` BIGINT(8) NOT NULL,
  FOREIGN KEY (`stamp_id`) REFERENCES `stamps`(`stamp_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `polling` (
  `key` INT NOT NULL,
  `last` datetime NOT NULL,
  PRIMARY KEY (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
